defmodule ElixirAwesome.Projects.Category do
  use Ecto.Schema
  alias ElixirAwesome.Projects.Project

  @fields [
    :description,
    :projects,
    :exist,
    :name
  ]

  @primary_key {:name, :string, autogenerated: false}
  @derive {Jason.Encoder, only: @fields}
  @derive {Phoenix.Param, key: :name}
  schema "categories" do
    field :description, :string
    field :exist, :boolean, default: false

    has_many :projects, Project, foreign_key: :category_name
  end
end
