defmodule ElixirAwesome.Projects.Project do
  use Ecto.Schema

  @fields [
    :category_name,
    :description,
    :stars_count,
    :last_commit,
    :name,
    :url
  ]

  @primary_key {:url, :string, autogenerated: false}
  @derive {Jason.Encoder, only: @fields}
  @derive {Phoenix.Param, key: :url}
  schema "projects" do
    field :description, :string
    field :exist, :boolean, default: false
    field :last_commit, :naive_datetime
    field :name, :string
    field :stars_count, :integer
    field :category_name, :string
  end
end
